export { default as Blog } from './blog/Blog'
export { default as Services } from './services/Services'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Support } from './support/Support'
export { default as Contact } from './contact/Contact'